env:
  browser: true
  es6: true
  node: true
extends:
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - typescript
  - "@typescript-eslint"
rules:
  quotes:
    - error
    - single
  semi:
    - error
    - always

